name: Train model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  Training:
    runs-on: macOS-latest
    if: "contains(github.event.head_commit.message, '#train')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install libraries
        run: |
          install.packages("devtools")
          install.packages("word2vec")
          devtools::install_github("laresbernardo/lares")
        shell: Rscript {0}
        
      - name: Run script
        run: Rscript -e 'source("model4/model4.R")'
