name: Train model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  Training:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-

      - name: Install libraries
        run: |
          devtools::install_github("laresbernardo/lares")
        shell: Rscript {0}
        
      - name: Run script
        run: |
          source("~/model2/model2.R")
        shell: Rscript {0}
