name: Train model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  Training:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install libraries
        run: |
          install.packages("devtools")
          devtools::install_github("laresbernardo/lares")
        shell: Rscript {0}
        
      - name: Run script
        run: Rscript -e 'source("model2/model2.R")'
